/*
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MathStandaloneSetup extends MathStandaloneSetupGenerated {

	def static void doSetup() {
		new MathStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
