/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MathIdeModule extends AbstractMathIdeModule {
}
